# 예외

개발자가 가장 신경 쓰기 귀찮아하는 것 중의 하나가 바로 예외처리다.

정상적인 결과와 흐름을 보여주는 코드를 만들기도 버거운데 예외상황까지 처리해야 한다는 사실때문이다.

그래서 예외와 관련된 코드는 자주 엉망이 되거나 무성의하게 만들어지기 쉽다.

때론 잘못된 예외처리 코드 때문에 찾기 힘든 버그를 낳을 수도 있고, 생각지 않았던 예외상황이 발생했을 때 상상 이상으로 난처해질 수도 있다.

이번 장(4장)에서는 JdbcTemplate을 대표로 하는 스프링의 데이터 엑세스 기능에 담겨 있는 예외처리와 관련된 접근 방법에 대해 알아본다.

## 초난감 예외처리

```java
  try {
    ...
  } catch(SQLException e) {
  }
```

보통 예외를 잡고는 아무것도 하지 않는다.

예외 발생을 무시해버리고 정상적인 상황인 것처럼 다음 라인으로 넘어가겠다는 분명한 의도가 있는게 아니라면 연습 중에도 절대 만들어서는 안 되는 코드다.

에외가 발생하면 그것을 catch 블록을 써서 잡아내는 것까지는 좋은데 그리고 아무것도 하지 않고 별문제 없는 것처럼 넘어가 버리는 건 정말 위험한 일이다.

원치 않는 예외가 발생하는 것보다 훨씬 나쁜 일이다.

왜냐하면 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다.

결국 발생한 예외로 인해 어떤 기능이 비정상적으로 동작하거나, 메모리나 리소스가 소진되거나, 예상치 못한 다른 문제를 일으킬 것이다.

더 큰 문제는 그 시스템 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 매우 힘들다는 점이다.

2가지 예시 상황이 더 있는데 위 코드와 마찬가지로 초난감한 코드이다.

```java
  try {
    ...
  } catch(SQLException e) {
    System.out.println(e);
  }
```

```java
  try {
    ...
  } catch(SQLException e) {
    e.printStackTrace();
  }
```

예외가 발생하면 화면에 출력되는데 뭐가 문제일까?

운영서버에 올라가면 콘솔 로그를 누군가가 계속 모니터링하지 않는 한 예외 코드는 심각한 폭탄으로 남아 있을 것이다.

예외는 처리돼야 한다.

예외를 처히라 때 반드시 지켜야 할 핵심 원칙은 한 가지다.

모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다.

SQLException이 발생하는 이유는 SQL에 문법 에러가 있거나 DB에서 처리할 수 없을 정도로 데이터 엑세스 로직에 심각한 버그가 있거나, 서버가 죽거나 네트워크가 끊기는 등의 심각한 상황이 벌어졌기 때문이다.

콘솔이나 로그에 예외 메시지를 출력하는 건 아무런 도움이 되지 않는다.

위 예외 코드보다 그나마 나은 예외처리 코드 하나를 작성한다.

```java
  try {
    ...
  } catch(SQLException e) {
    e.printStackTrace();
    System.exit(1);
  }
```

예외를 무시하거나 잡아먹어 버리는 코드는 만들지 말라는 뜻이다.

굳이 예외를 잡아서 뭔가 조치를 취할 방법이 없다면 잡지 말아야 한다.

메소드에 throws SQLException을 선언해서 메소드 밖으로 던지고 자신을 호출한 코드에 예외처리 책임을 전가해버려야 한다.

### 무의미하고 무책임한 throws

![image](https://github.com/user-attachments/assets/302ae8c1-f527-4b80-b6b7-ddc5f43f8221)

API 등에서 발생하는 예외를 일일이 catch하기도 귀찮고, 별 필요도 없으며 매번 정확하게 예외 이름을 적어서 선언하기도 귀찮으니 아예 throws Exception이라는, 모든 예외를 무조건 던져버리는 선언을 모든 메소드에 기계적으로 넣는 것이다.

예외를 흔적도 없이 먹어치우는 예외 블랙홀보다는 낫긴 하지만 이런 무책임한 throws 선언도 심각한 문제점이 있다.

자신이 사용하려고 하는 메소드에 throws Exception이 선언되어 있다고 생각해보자.

그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다.

결국 이런 메소드를 사용하는 메소드에서도 역시 throws Exception을 따라서 붙이는 수밖에 없다.

결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다룰 수 있는 기회를 박탈당한다.

예외를 무시해버리는 첫 번째 문제보다는 낫다고 하지만 이런 코드도 매우 안 좋은 예외처리 방법이다.

이 두 가지 나쁜 습관은 어떤 경우에도 용납하지 않아야 한다.

## 예외의 종류와 특징
그렇다면 예외를 어떻게 다뤄야 할까?

가장 큰 이슈는 체크 예외(checked exception)라고 불리는 명시적인 처리가 필요한 예외를 사용하고 다루는 방법이다.

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.
- Error
  java.lang.Error 클래스의 서브클래스들이다.

  에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다.

  그래서 주로 자바 VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다.

  따라서 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다.

- Exception과 체크 예외
  java.lang.Exeption 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.

  Exception 클래스는 다시 체크 예외(checked exception)와 언체크 예외(unchecked exception)로 구분된다.

  전자는 Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것들이고, 후자는 RuntimeException을 상속한 클래스들을 말한다.

  RuntimeException은 Exception의 서브클래스이므로 Exception의 일종이긴 하지만 자바는 이 RuntimeException과 그 서브클래스는 특별하게 다룬다.

  ![image](https://github.com/user-attachments/assets/6a50f3ff-e12e-4d99-b10c-3623b4726536)

  일반적으로 예외라고 하면 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다.

  체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다.

  사용할 메소드가 체크 예외를 던진다면 이를 catch 문으로 잡든지, 아니면 다시 throws를 정의해서 메소드 밖으로 던져야 한다.

  그렇지 않으면 컴파일 에러가 발생한다.

- RuntimeException과 언체크/런타임 예외
  java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라고 불린다.

  에러와 마찬가지로 이 런타임 예외는 catch 문으로 잡거나 throws로 선언하지 않아도 된다.

  물론 명시적으로 잡거나 throws로 선언해줘도 상관없다.

  런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다.

  대표적으로 오브젝트를 할당하지 않은 레퍼런스 변수를 사용하려고 시도했을 때 발생하는 NullPointerException이나, 허용되지 않는 값을 사용해서 메소드를 호출할 때 발생하는 IllegalArgumentException 등이 있다.

  이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다.

  피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이 런타임 예외다.

## 예외처리 방법

### 예외 복구

첫 번째 예외처리 방법은 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다.

예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해주는 것이다.

이런 경우 예외상황은 다시 정상으로 돌아오고 예외를 복구했다고 볼 수 있다.

단, IOException 에러 메시지가 사용자에게 그냥 던져지는 것은 예외 복구라고 볼 수 없다.

예외가 처리됐으면 비록 기능적으로는 사용자에게 예외상황으로 비쳐도 애플리케이션에서는 정상적으로 설계된 흐름을 따라 진행돼야 한다.

예외처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다.

API를 사용하는 개발자로 하여금 예외상황이 발생할 수 있음을 인식하도록 이에 대한 적절한 처리를 시도해보도록 요구하는 것이다.

통제 불가능한 외부 요인으로 인해 예외가 발생하면 MAX_RETRY만큼 재시도를 하는 것도 좋다.

사전에 미리 성공 여부를 확인할 수 없고, 재시도가 의미 있는 경우라면 이렇게 최대 횟수만큼 반복적으로 시도함으로써 예외상황에서 복구되게 할 수 있다.

```java
int maxRetry = MAX_RETRY;

while(maxRetry -- > 0) {
  try {
    ...      // 예외가 발생할 가능성이 있는 시도
    return;  // 작업 성공
  } catch(SomeException e) {
    // 로그 출력, 정해진 시간만큼 대기
  } finally {
    // 리소스 반납, 정리 작업
  }
} throws enw RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```

### 예외처리 회피

두 번째 방법은 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다.

throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것이다.

예외를 자신이 처리하지 않고 회피하는 방법이다.

예외처리를 회피하려면 반드시 다른 오브젝트나 메소드가 예외를 대신 처리할 수 있도록 다음 코드와 같이 던져줘야 한다.

```java
  public void add() throws SQLException {
    // JDBC API
  }
```

```
  public void add() throws SQLException {
    try {
      // JDBC API
    } catch(SQLException e) {
      // 로그 출력
      throw e;
    }
  }
```

콜백 오브젝트의 메소드는 모두 throws SQLException이 붙어 있다.

SQLException을 처리하는 일은 콜백 오브젝트의 역할이 아니라고 보기 때문이다.

콜백 오브젝트의 메소드는 SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다.

하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다.

예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다.

콜백/템플릿처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야 한다.

### 예외 전환

마지막으로 예외를 처리하는 방법은 예외 전환(exception translation)을 하는 것이다.

예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것이다.

하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.

예외 전환은 보통 두 가지 목적으로 사용된다.

첫째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서다.

API가 발생하는 기술적인 로우레벨을 상황에 적합한 의미를 가진 예외로 변경하는 것이다.

서비스 계층 오브젝트에서 SQLException의 원인을 해석해서 대응하는 것도 불가능하지는 않지만, 특정 기술의 정보를 해석하는 코드를 비즈니스 로직을 담은 서비스 계층에 두는 건 매우 어색하다.

따라서 DAO 메소드에서 기술에 독립적이며 의미가 분명한 예외로 전환해서 던져줄 필요가 있다.

```java
public void add(User user) throws DuplicateUserIdException, SQLException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
  } catch(SQLException e) {
    // ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
    if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throws DuplicateUserIdException();
    else
      throw e; // 그 외 에러는 SQLException 그대로
  }
}
```

보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외로 만드는 것이 좋다.

중첩 예외는 getCause() 메소드를 이용해서 처음 발생한 예외가 무엇인지 확인할 수 있다.

중첩 예외는 새로운 예외를 만들면서 생성자나 initCause() 메소드로 근본 원인이 되는 예외를 넣어주면 된다.

```java
  catch(SQLException e) {
    ...
    throws DuplicateUserIdException(e);
  }
```

```java
  catch(SQLException e) {
  ...
  throw DuplicateUserIdException().initCause(e);
```

두 번째 전환 방법은 예외를 처리하기 쉽고 단순하게 만들기 위해 포장하는 것이다.

중첩 예외를 이용해 새로운 예외를 만들고 원인이 되는 예외를 내부에 담아서 던지는 방식은 같다.

하지만 의미를 명확하게 하려고 다른 예외로 전환하는 것이 아니다.

주로 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다.

```java
  try {
    ...
  } catch(NamingException ne) {
    throw new EJBException(ne);
  } catch(SQLException se) {
    throw new EJBException(se);
  } catch(RemoteException re) {
    throw new EJBException(re);
  }
```

EJBException은 RuntimeException 클래스를 상속한 런타임 예외다.

이렇게 런타임 예외로 만들어서 전달하면 EJB는 이를 시스템 익셉션으로 인식하고 트랜잭션을 자동으로 롤백해준다.

런타임 예외이기 때문에 EJB 컴포넌트를 사용하는 EJB나 클라이언트에서 일일이 예외를 잡거나 다시 던지는 수고를 할 필요가 없다.

이런 예외는 잡아도 복구할 만한 방법이 없기 때문이다.

반대로 애플리케이션 로직상에서 예외조건이 발견되거나 예외상황이 발생할 수도 있다.

이런 것은 API가 던지는 예외가 아니라 애플리케이션 코드에서 의도적으로 던지는 예외다.

이때는 체크 예외를 사용하는 것이 적절하다.

비즈니스적인 의미가 있는 예외는 이에 대한 적절한 대응이나 복구 작업이 필요하기 때문이다.

일반적으로 체크 예외를 계속 throws를 사용해 넘기는 건 무의미하다.

메소드 선언은 지저분해지고 아무런 장점이 없다.

어차피 복구가 불가능한 예외라면 가능한 한 빨리 런타임 예외로 포장해 던지게 해서 다른 계층의 메소드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 해줘야 한다.

대부분 서버환경에서는 애플리케이션 코드에서 처리하지 않고 전달된 예외들을 일괄적으로 다룰 수 있는 기능을 제공한다.

어차피 복구하지 못할 예외라면 애플리케이션 코드에서는 런타임 예외로 포장해서 던져버리고, 예외처리 서비스 등을 이용해 자세한 로그를 남기고, 관리자에게는 메일 등으로 통보해주고, 사용자에게는 친절한 안내 메시지를 보여주는 식으로 처리하는 게 바람직하다.

## 예외처리 전략

### 런타임 예외의 보편화

일반적으로는 체크 예외가 일반적인 예외를 다루고, 언체크 예외는 시스템 장애나 프로그램상의 오류에 사용한다.

문제는 체크 예외는 복구할 가능성이 조금이라도 있는,  말 그대로 예외적인 상황이기 때문에 자바는 이를 처리하는 catch 블록이나 throws 선언을 강제하고 있다는 점이다.

독립형 애플리케이션과 달리 서버의 특정 계층에서 예외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니케이션하면서 예외상황을 복구할 수 있는 방법이 없다.

차라리 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는게 좋다.

또는 프로그램의 오류나 외부 환경으로 인해 예외가 발생하는 경우라면 빨리 해당 요청의 작업을 취소하고 서버 관리자나 개발자에게 통보해주는 편이 좋다.

자바의 환경이 서버로 이동하면서 체크 예외의 활용도와 가치는 점점 떨어지고 있다.

자칫하면 throws Exception으로 점철된 아무런 의미도 없는 메소드들을 낳을 뿐이다.

그래서 대응이 불가능한 체크 예외라면 빨리 런타임 예외로 전환해서 던지는 것이 낫다.

최근 등장하는 표준 스펙 또는 오픈소스 프레임워크에서는 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화되고 있다.

예전에는 복구할 가능성이 조금이라도 있다면 체크 예외로 만든다고 생각했는데, 지금은 항상 복구할 수 있는 예외가 아니라면 일단 언체크 예외로 만드는 경향이 있다.

언체크 예외라도 필요하다면 얼마든지 catch 블록으로 잡아서 복구하거나 처리할 수 있다.

언체크 예외라도 필요하다면 얼마든지 catch 블록으로 잡아서 복구하거나 처리할 수 있다.

하지만 대개는 복구 불가능한 상황이고 보나마나 RuntimeException 등으로 포장해서 던져야 할 테니 아예 API 차원에서 런타임 예외를 던지도록 만드는 것이다.

### add() 메소드의 예외처리

SQLException은 대부분 복구 불가능한 예외이므로 잡아봤자 처리할 것도 없고, 결국 throws를 타고 계속 앞으로 전달되다가 애플리케이션 밖으로 던져질 것이다.

그럴 바에는 그냥 런타임 예외로 포장해 던져버려서 그 밖의 메소드들이 신경 쓰지 않게 해주는 편이 낫다.

DuplicateduserIdException 처럼 의미 있는 예외는 add() 메소드를 바로 호출한 오브젝트 대신 더 앞단의 오브젝트에서 다룰 수도 있다.

어디에서든 DuplicatedUserIdException을 잡아서 처리할 수 있다면 굳이 체크 예외로 만들지 않고 런타임 예외로 만드는 게 낫다.

그래야 add() 메소드를 사용하는 코드를 만드는 개발자에게 의미 있는 정보를 전달해줄 수 있다.

이 방법을 이용해 add() 메소드를 수정한다.

```java
public class DuplicateUserIdException extends RuntimeException {
  public DuplicateUserIdException(Throwable cause) {
    super(cause);
  }
}
```

먼저 사용자 아이디가 중복됐을 때 사용하는 DuplicateUserIdException을 만든다.

RuntimeException을 상속한 런타임 예외로 만든다.

중첩 예외를 만들 수 있도록 생성자를 추가해주는 것을 잊지 말자.

메시지나 예외상황을 전달하는 데 필요한 정보를 더 넣을 수도 있다.

이제 특별한 의미를 가지는 DuplicatedUserIdException 외에 시스템 예외에 해당하는 SQLException은 언체크 예외가 됐다.

따라서 메소드 선언의 throws에 포함시킬 필요가 없다.

반면에 역시 언체크 예외로 만들어지긴 했지만 add() 메소드를 사용하는 쪽에서 아이디 중복 예외를 처리하고 싶은 경우 활용할 수 있음을 알려주도록 DuplicatedUserIdException을 메소드의 throws 선언에 포함시킨다.

이렇게 정리한 add() 메소드다.

```java
public void add(User user) throws DuplicateUserIdException {
  try {
    // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는
    // 그런 기능을 가진 다른 SQLException을 던지는 메소드를 호출하는 코드
  } catch(SQLException e) {
    // ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
    if (e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY)
      throws new DuplicateUserIdException();
    else
      throw new RuntimeException(e); // 예외 포장
  }
}
```

이제 이 add() 메소드를 사용하는 오브젝트는 SQLException을 처리하기 위해 불필요한 throws 선언을 할 필요는 없으면서, 필요한 경우 아이디 중복 상황을 처리하기 위해 DuplicatedUserIdException을 이용할 수 있다.

이렇게 런타임 예외를 일반화해서 사용하는 방법은 여러모로 장점이 많다.

단, 런타임 예외로 만들었기 때문에 사용에 더 주의를 기울일 필요도 있다.

컴파일러가 예외처리를 강제하지 않으므로 신경 쓰지 않으면 예외상황을 충분히 고려하지 않을 수도 있기 때문이다.

런타임 예외를 사용하는 경우에는 API 문서나 레퍼런스 문서 등을 통해, 메소드를 사용할 때 발생할 수 있는 예외의 종류와 원인, 활용 방법을 자세히 설명해둬야 한다.

### 애플리케이션 예외

시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch 해서 무엇인가 조치를 취하도록 요구하는 예외도 있다.

이런 예외들을 일반적으로 애플리케이션 예외라고 한다.

메소드를 설계하는 방법이 두 가지 있다.

첫 번째 방법은 각각 다른 종류의 리턴 값을 돌려주는 것이다.

경우에 따라 작업 흐름이 달라져야 하기 때문이다.

물론 이것은 시스템 오류가 아니므로 기술적으로 보면 두 가지 경우 모두 정상 흐름이다.

하지만 이렇게 리턴 값으로 결과를 확인하고, 예외상황을 체크하면 불편한 점도 있다.

우선 예외상황에 대한 리턴 값을 명확하게 코드화하고 잘 관리하지 않으면 혼란이 생길 수 있다.

정상적인 처리가 안 됐을 때 전달하는 값의 표준 같은 것은 없다.

일관된 예외상황에서의 결과 값에 대한 정책이 완벽하게 갖춰져 있고, 사전에 상수로 정의해둔 표준 코드를 사용하지 않는다면 자칫 개발자 사이의 의사소통 문제로 인해 제대로 동작하지 않을 위험이 있다.

또 한 가지 문제는 결과 값을 확인하는 조건문이 자주 등장한다는 점이다.

이런 식으로 결과를 돌려주는 메소드를 연이어 사용하면 if 블록이 범벅된 코드가 이어질지 모른다.

코드는 지저분해지고 흐름을 파악하고 이해하기 힘들어질 것이다.

두 번째 방법은 정상적인 흐름을 따르는 코드는 그대로 두고, 잔고 부족과 같은 예외 상황에서는 비즈니스적인 의미를 띤 예외를 던지도록 만드는 것이다.

예외상황을 처리하는 catch 블록을 메소드 호출 직후에 둘 필요는 없다.

정상적인 흐름을 따르지만 예외가 발생할 수 있는 코드를 try 블록 안에 깔끔하게 정리해두고 예외상황에 대한 처리는 catch 블록에 모아둘 수 있기 때문에 코드를 이해하기도 편하다.

이때 사용하는 예외는 의도적으로 체크 예외로 만든다.

그래서 개발자가 잊지 않고 자주 발생 가능한 예외상황에 대한 로직을 구현하도록 강제해주는게 좋다.

무책임하게 throws Exception을 습관적으로 달아놓은 경우라면 이마저도 놓칠 가능성이 있긴 하지만, 기본적으로 런타임 예외로 만들어두는 것보다는 상대적으로 안전하다.

## SQLException은 어떻게 됐나?

먼저 생각해볼 사항은 SQLException은 과연 복구가 가능한 예외인가이다.

99%의 SQLException은 코드 레벨에서는 복구할 방법이 없다.

프로그램의 오류 또는 개발자의 부주의 때문에 발생하는 경우이거나, 통제할 수 없는 외부상황 때문에 발생하는 것이다.

시스템의 예외라면 당연히 애플리케이션 레벨에서 복구할 방법이 없다.

관리자나 개발자에게 빨리 예외가 발생했다는 사실이 알려지도록 전달하는 방법밖에는 없다.

마찬가지로 애플리케이션 코드의 버그나 미처 다루지 않았던 범위를 벗어난 값 때문에 발생한 예외도 역시 복구할 방법이 없다.

대부분 SQLException은 복구가 불가능하다.

따라서 예외처리 전략을 적용해야 한다.

필요도 없는 기계적인 throws 선언이 등장하도록 방치하지 말고 가능한 빨리 언체크/런타임 예외로 전환해줘야 한다.

## DAO 인터페이스와 DataAccessException 계층구조

### DAO 인터페이스와 구현의 분리
DAO를 굳이 따로 만들어서 사용하는 이유는 무엇일까?

가장 중요한 이유는 데이터 엑세스 로직을 담은 코드를 성격이 다른 코드에서 분리해놓기 위해서다.

또한 분리된 DAO는 전략 패턴을 적용해 구현 방법을 변경해서 사용할 수 있게 만들기 위해서이기도 하다.

DAO를 사용하는 쪽에서는 DAO가 내부에서 어떤 데이터 엑세스 기술을 사용하는지 신경 쓰지 않아도 된다.

User와 같은 자바 빈으로 만들어진, 특정 기술에 독립적인 단순한 오브젝트를 주고받으면서 데이터 엑세스 기능을 사용하기만 하면 된다.

DAO는 인터페이스를 사용해 구체적인 클래스 정보와 구현 방법을 감추고, DI를 통해 제공되도록 만드는 것이 바람직하다.

인터페이스로 추상화하고, 일부 기술에서 발생하는 체크 예외를 런타임 예외로 전환하는 것만으론 불충분하다.

## 기술에 독립적인 UserDAO 만들기

### 인터페이스 적용
```java
public interface UserDao {
  void add(User user);
  User get(String id);
  List<User> getAll();
  ...
}
```

public 접근자를 가진 메소드이긴 하지만 UserDao의 setDataSource() 메소드는 인터페이스에 추가하면 안 된다는 사실에 주의하자.

setDataSource() 메소드는 UserDao의 구현 방법에 따라 변경될 수 있는 메소드이고, UserDao를 사용하는 클라이언트가 알고 있을 필요도 없기에 포함시키지 않는다.

```java
public class UserDaoJdbc implements UserDao {
  ...
}
```

### 테스트 보안

```java
public class UserDaoTest {
  @Autowired
  private UserDao dao; // UserDaoJdbc로 변경해야 하나?
}
```

@Autowired는 스프링의 컨텍스트 내에서 정의된 빈 중에서 인스턴스 변수에 주입 가능한 타입의 빈을 찾아준다.

UserDao는 UserDaoJdbc가 구현한 인터페이스이므로 아무런 문제가 없다.

UserDaoJdbc 오브젝트는 UserDao 타입이기 때문이다.

# 정리

- 예외를 잡아서 아무런 조취를 취하지 않거나 의미 없는 throws 선언을 남발하는 것은 위험하다.
- 예외는 복구하거나 예외처리 오브젝트로 의도적으로 전달하거나 적절한 예외로 전환해야 한다.
- 좀 더 의미 있는 예외로 변경하거나, 불필요한 catch/throws를 피하기 위해 런타임 예외로 포장하는 두 가지 방법의 예외 전환이 있다.
- 복구할 수 없는 예외는 가능한 한 빨리 런타임 예외로 전환하는 것이 바람직하다.
- 애플리케이션의 로직을 담기 위한 예외는 체크 예외로 만든다.
- JDBC의 SQLException은 대부분 복구할 수 없는 예외이므로 런타임 예외로 포장해야 한다.
- SQLException의 에러 코드는 DB에 종속되기 때문에 DB에 독립적인 예외로 전환될 필요가 있다.
- 스프링은 DataAccessException을 통해 DB에 독립적으로 적용 가능한 추상화된 런타임 예외 계층을 제공한다.
- DAO를 데이터 엑세스 기술에서 독립시키려면 인터페이스 도입과 런타임 예외 전환, 기술에 독립적인 추상화된 예외로 전환이 필요하다.














